### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Include `XXX` in list of target words and call out that match is case
sensitive.

@codeclimate/review

### CODE REVIEW

**Comment by wfleming** [comment]
:+1: 

I just noticed that the wording of the README refers to us finding *comments*, which isn't actually accurate. Thoughts on rewording that as well?

**Comment by ABaldwinHunter** [comment]
@wfleming good catch.

:+1: implementing

**Comment by ABaldwinHunter** [comment]
@wfleming updated!

**Comment by wfleming** [comment]
LGTM

**Pull request merged**
