### PR TITLE
Allow to set the paths via the 'engine.fixme.config.include_paths' variable

### PR DESCRIPTION
**Pull request by zetaron**
As I was in deer need to limit the scope of processed files, I added a
way to only check certain paths.

### CODE REVIEW

**Comment by wfleming** [comment]
Hi @zetaron,

Thanks for the patch, but this isn't functionality we want to add right now. In general, we encourage users to use [`exclude_paths` in their `.codeclimate.yml`](https://docs.codeclimate.com/docs/excluding-files-and-folders#section-exclude-paths-for-specific-engines) to control which files an engine will analyze.

If that isn't suitable for your needs right now, I'd love to get more feedback about your use case.

Thanks!

**Comment by zetaron** [comment]
Hey @wfleming, 

It actually isn't suitable. 
I'm maintaining several Magento 1x projects which are host for several extensions, which I am not the maintainer of. 
But I want to at least use the codeclimate tool chain to rank my team's development. 
And thus just need to process a very limited number of directories. 

Therefore it would be great if you could accept the PR.
I'd provide similar functionality for the other engines we use. 

On June 3, 2016 8:59:44 PM GMT+02:00, Will Fleming <notifications@github.com> wrote:
>Hi @zetaron,
>
>Thanks for the patch, but this isn't functionality we want to add right
>now. In general, we encourage users to use [`exclude_paths` in their
>`.codeclimate.yml`](https://docs.codeclimate.com/docs/excluding-files-and-folders#section-exclude-paths-for-specific-engines)
>to control which files an engine will analyze.
>
>If that isn't suitable for your needs right now, I'd love to get more
>feedback about your use case.
>
>Thanks!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/codeclimate/codeclimate-fixme/pull/39#issuecomment-223664631

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wfleming** [comment]
Thanks for the explanation, @zetaron. We have concerns about implementing this piece-meal and for each engine individually: that would lead to needing to maintain many different implementations & probably behavior differences between different engines, which we'd like to avoid for this kind of functionality. We're discussing ways of addressing this in the CLI itself so all engines would be able to benefit from the change immediately & the behavior would be consistent. Hopefully I'll have some more details for you on that soon.

**Comment by wfleming** [comment]
@zetaron We just released an update for our CLI (0.34.0) and for our hosted analysis with support for negated exclude patterns, similar to how `.gitignore` works.

With this functionality, you can ignore *everything* for an engine & then un-ignore the specific files or glob patterns you care about. e.g.

```yaml
engines:
  fixme:
    enabled: true
    exclude_paths:
      - "*"
      - "!somefile.txt"
      - "!something/else"
```

Thanks for your patience on this. Let me know if you run into trouble using this.

**Comment by zetaron** [comment]
@wfleming thanks for the heads up, will check it out.

**Pull request closed without merging**
