### PR TITLE
Modify index.js to support include_paths

### PR DESCRIPTION
**Pull request by jacobi007**
As listed in [spec](https://github.com/codeclimate/spec/blob/master/SPEC.md)

### CODE REVIEW

**Comment by fhwang** [comment]
It bums me out that we don't have real specs for these JS-driven engines. That being said, assuming the Circle CI issue can be fixed, LGTM.

**Comment by jacobi007** [comment]
@fhwang I think we had a similar problem in codeclimate CLI repo, it was resolved by editing the `circle.yml`. All gcloud related commands were removed from `pre` and are used only during deployment. Check it out [here](https://github.com/codeclimate/codeclimate/commits/78525dc977dafa63e271cae0d0db30c34771ad52/circle.yml)

**Comment by ABaldwinHunter** [comment]
@jacobi007 sorry! I didn't realize that [github commit words](https://github.com/codeclimate/codeclimate-fixme/pull/9) could deal the samurai death star of closing a PR.

I updated the circle file on this repo, so if you rebase, we should see tests pass and then can merge on green.

**Comment by jacobi007** [comment]
@ABaldwinHunter done!

**Pull request merged**
